<?xml version="1.0" encoding="utf-8"?><Database Name="iws" Class="IWSDataEntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\mssqllocaldb;Initial Catalog=iws;Integrated Security=True;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="iwsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.account" Member="accounts">
    <Type Name="account">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="groupid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dateofopen" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="dateofclose" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vendorinvoice" Member="vendorinvoices">
    <Type Name="vendorinvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="store" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.article" Member="articles">
    <Type Name="article">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="avgprice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="salesprice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="qttyunit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="packunit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="groupid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="vat" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.bank" Member="banks">
    <Type Name="bank">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.bankaccount" Member="bankaccounts">
    <Type Name="bankaccount">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bic" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="debit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="credit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.company" Member="companies">
    <Type Name="company">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bankaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="purchasingclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="salesclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="paymentclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="settlementclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="periode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nextperiode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="taxcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="vatcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.costcenter" Member="costcenters">
    <Type Name="costcenter">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.country" Member="countries">
    <Type Name="country">
      <Column Name="code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="population" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gnp" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="accountid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.goodreceiving" Member="goodreceivings">
    <Type Name="goodreceiving">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="store" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.inventoryinvoice" Member="inventoryinvoices">
    <Type Name="inventoryinvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="store" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.linegoodreceiving" Member="linegoodreceivings">
    <Type Name="linegoodreceiving">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="item" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="quantity" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="vat" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.lineinventoryinvoice" Member="lineinventoryinvoices">
    <Type Name="lineinventoryinvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="item" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.linepayment" Member="linepayments">
    <Type Name="linepayment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="side" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="oaccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.linepurchaseorder" Member="linepurchaseorders">
    <Type Name="linepurchaseorder">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="item" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vat" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.linevendorinvoice" Member="linevendorinvoices">
    <Type Name="linevendorinvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="side" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="oaccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Controller" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Roles" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Disable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.payment" Member="payments">
    <Type Name="payment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="store" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.person" Member="persons">
    <Type Name="person">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="age" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.purchaseorder" Member="purchaseorders">
    <Type Name="purchaseorder">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="store" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.quantityunit" Member="quantityunits">
    <Type Name="quantityunit">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.stock" Member="stocks">
    <Type Name="stock">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="itemid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="storeid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="minstock" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.store" Member="stores">
    <Type Name="store">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="accountid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.supplier" Member="suppliers">
    <Type Name="supplier">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="accountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vat" Member="vats">
    <Type Name="vat">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[percent]" Member="percent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="inputvataccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="outputvataccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="revenueaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="stockaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="expenseaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>