#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 5 "..\..\Views\Companies\SetLogo.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Companies\SetLogo.cshtml"
    using IWSProject.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Companies/SetLogo.cshtml")]
    public partial class _Views_Companies_SetLogo_cshtml : System.Web.Mvc.WebViewPage<SetLogoViewModel>
    {
        public _Views_Companies_SetLogo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"accountHeader\"");

WriteLiteral(">\r\n   <h2>");

            
            #line 8 "..\..\Views\Companies\SetLogo.cshtml"
  Write(IWSLocalResource.SetLogo);

            
            #line default
            #line hidden
WriteLiteral(" </h2>\r\n</div>\r\n\r\n");

            
            #line 11 "..\..\Views\Companies\SetLogo.cshtml"
  
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function OnFilesUploadComplete(s, e) {
        var data = e.callbackData.split('|');
        for (var i = 0; i < data.length; i += 2) {
            var file = data[i];
            var url = data[i + 1];
            var link = document.createElement('A');
            link.innerHTML = file;
            link.setAttribute('href', url);
            link.setAttribute('target', '_blank');
            var fileContainer = document.getElementById('fileContainer');
            fileContainer.appendChild(link);
            fileContainer.appendChild(document.createElement('BR'));
        }
    }
</script>

");

            
            #line 33 "..\..\Views\Companies\SetLogo.cshtml"
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Companies\SetLogo.cshtml"
     using (Html.BeginForm())
    {
        
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Companies\SetLogo.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Companies\SetLogo.cshtml"
                                
        
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Companies\SetLogo.cshtml"
   Write(Html.DevExpress().FormLayout(settings =>
   {
   settings.Name = "formSetLogo";

   settings.Items.AddGroupItem(group =>
   {
   group.Caption = IWSLocalResource.CompanyInfo;
   group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;

   group.Items.Add(combo =>
   {
       combo.Name = "CompanyID";
       combo.Caption = IWSLocalResource.company;
       combo.NestedExtension().ComboBox(s =>
       {
           s.Properties.TextField = "Name";
           s.Properties.ValueField = "Name";
           s.Properties.ValueType = typeof(string);
           //s.Properties.DataSource = ViewData["Companies"];
           s.Properties.DataSource = IWSLookUp.GetCompanies(); //ViewData["Companies"];
           s.Properties.Columns.Add("id").Caption = IWSLocalResource.id;
           s.Properties.Columns.Add("name").Caption = IWSLocalResource.company;
           s.Properties.DropDownStyle = DropDownStyle.DropDownList;
       });
   });

   //group.Items.Add(button =>
   //{
   //    button.Name = "btnLogo";

   //    button.Caption = "  ";
   //    button.NestedExtension().Button(b =>
   //    {
   //        b.Text = IWSLocalResource.ChooseLogo;
   //    });
   //});
    
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\Companies\SetLogo.cshtml"
        
//    @using(Html.BeginForm("UploadControlUpload", "Home"))
//{
//        @Html.DevExpress().UploadControl(settings =>
//        {
//            settings.Name = "UploadControl";
//            settings.ShowUploadButton = true;
//            settings.ShowProgressPanel = true;
//            settings.AdvancedModeSettings.EnableMultiSelect = true;
//            settings.AdvancedModeSettings.EnableFileList = true;
//            settings.AdvancedModeSettings.EnableDragAndDrop = true;
//            settings.UploadMode = DevExpress.Web.UploadControlUploadMode.Advanced;
//            settings.ValidationSettings.Assign(MyUploadControlValidationSettings.Settings);
//            settings.ClientSideEvents.FilesUploadComplete = "OnFilesUploadComplete";
//        }).GetHtml()
//}
    
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Companies\SetLogo.cshtml"
        
        group.Items.Add(upload =>
        {
            upload.Name = "UploadControl";
            upload.NestedExtension().UploadControl(u =>
            {
                u.ShowTextBox = true;
                u.ShowUploadButton = true;
                u.ShowProgressPanel = true;
                u.AdvancedModeSettings.EnableDragAndDrop = true;
                u.UploadMode = UploadControlUploadMode.Advanced;
                u.ValidationSettings.Assign(IWSProject.Models.IWSLookUp.Settings);
                u.ClientSideEvents.FileUploadComplete = "OnFilesUploadComplete";
            });

        });

    });

       settings.Items.AddGroupItem(group =>
       {
           group.Caption = IWSLocalResource.CompanyLogo;
           group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
           group.Items.Add(picture =>
           {
               picture.Name = "LogoBinary";
               picture.Caption = "";
               picture.NestedExtension().BinaryImage(b =>
               {

               });
           });

       });

       settings.Items.AddGroupItem(group =>
       {
           group.Caption = "  ";
           group.GroupBoxDecoration = GroupBoxDecoration.HeadingLine;
           group.Items.Add(i =>
           {
               i.Caption = "  ";
               i.NestedExtension().Button(b =>
               {
                   b.Name = "signUp";
                   b.Text = IWSLocalResource.Validate;
                   b.UseSubmitBehavior = true;
                   b.Width = Unit.Pixel(120);
               });
           });
       });

   }).GetHtml());

            
            #line default
            #line hidden
            
            #line 140 "..\..\Views\Companies\SetLogo.cshtml"
               
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
