<?xml version="1.0" encoding="utf-8"?><Database Name="iws" Class="IWSDataProviderDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\mssqllocaldb;Initial Catalog=iws;Integrated Security=True;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="IWSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="groupid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dateofopen" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="dateofclose" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Account_PeriodicAccountBalance" Member="PeriodicAccountBalances" ThisKey="id" OtherKey="AccountId" Type="PeriodicAccountBalance" />
    </Type>
  </Table>
  <Table Name="dbo.VendorInvoice" Member="VendorInvoices">
    <Type Name="VendorInvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Article" Member="Articles">
    <Type Name="Article">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="avgprice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="salesprice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="qttyunit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="packunit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="groupid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VatCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsService" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Article_LineGoodReceiving" Member="LineGoodReceivings" ThisKey="id" OtherKey="item" Type="LineGoodReceiving" />
      <Association Name="Article_Stock" Member="Stocks" ThisKey="id" OtherKey="itemid" Type="Stock" />
      <Association Name="Vat_Article" Member="Vat" ThisKey="VatCode" OtherKey="id" Type="Vat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Bank" Member="Banks">
    <Type Name="Bank">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BankAccount" Member="BankAccounts">
    <Type Name="BankAccount">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bic" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="debit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="credit" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="bankaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="purchasingclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="salesclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="paymentclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="settlementclearingaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="periode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nextperiode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="taxcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="vatcode" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CostCenter" Member="CostCenters">
    <Type Name="CostCenter">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="population" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gnp" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="accountid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GoodReceiving" Member="GoodReceivings">
    <Type Name="GoodReceiving">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="GoodReceiving_LineGoodReceiving" Member="LineGoodReceivings" ThisKey="id" OtherKey="transid" Type="LineGoodReceiving" />
      <Association Name="Store_GoodReceiving" Member="Store1" ThisKey="store" OtherKey="id" Type="Store" IsForeignKey="true" />
      <Association Name="Supplier_GoodReceiving" Member="Supplier" ThisKey="account" OtherKey="id" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InventoryInvoice" Member="InventoryInvoices">
    <Type Name="InventoryInvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LineGoodReceiving" Member="LineGoodReceivings">
    <Type Name="LineGoodReceiving">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="quantity" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="VatCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Article_LineGoodReceiving" Member="Article" ThisKey="item" OtherKey="id" Type="Article" IsForeignKey="true" />
      <Association Name="GoodReceiving_LineGoodReceiving" Member="GoodReceiving" ThisKey="transid" OtherKey="id" Type="GoodReceiving" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LineInventoryInvoice" Member="LineInventoryInvoices">
    <Type Name="LineInventoryInvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="vat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LinePayment" Member="LinePayments">
    <Type Name="LinePayment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="side" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="oaccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LinePurchaseOrder" Member="LinePurchaseOrders">
    <Type Name="LinePurchaseOrder">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="item" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="vat" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LineVendorInvoice" Member="LineVendorInvoices">
    <Type Name="LineVendorInvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="transid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="side" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="oaccount" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="duedate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Controller" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Roles" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Disable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HasAccess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payment" Member="Payments">
    <Type Name="Payment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PeriodicAccountBalance" Member="PeriodicAccountBalances">
    <Type Name="PeriodicAccountBalance">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Periode" Type="System.String" DbType="NChar(6)" CanBeNull="true" />
      <Column Name="Debit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Credit" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Account_PeriodicAccountBalance" Member="Account" ThisKey="AccountId" OtherKey="id" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="age" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PurchaseOrder" Member="PurchaseOrders">
    <Type Name="PurchaseOrder">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="oid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="account" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuantityUnit" Member="QuantityUnits">
    <Type Name="QuantityUnit">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Stock" Member="Stocks">
    <Type Name="Stock">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="itemid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="storeid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="minstock" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="Article_Stock" Member="Article" ThisKey="itemid" OtherKey="id" Type="Article" IsForeignKey="true" />
      <Association Name="Store_Stock" Member="Store" ThisKey="storeid" OtherKey="id" Type="Store" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Store" Member="Stores">
    <Type Name="Store">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="accountid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Store_GoodReceiving" Member="GoodReceivings" ThisKey="id" OtherKey="store" Type="GoodReceiving" />
      <Association Name="Store_Stock" Member="Stocks" ThisKey="id" OtherKey="storeid" Type="Stock" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="accountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Supplier_GoodReceiving" Member="GoodReceivings" ThisKey="id" OtherKey="account" Type="GoodReceiving" />
    </Type>
  </Table>
  <Table Name="dbo.Vat" Member="Vats">
    <Type Name="Vat">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="modelid" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PVat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="inputvataccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="outputvataccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="revenueaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="stockaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="expenseaccountid" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Vat_Article" Member="Articles" ThisKey="id" OtherKey="VatCode" Type="Article" />
    </Type>
  </Table>
</Database>