#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using DevExpress.XtraReports;
    using DevExpress.XtraReports.UI;
    using DevExpress.XtraReports.Web;
    using DevExpress.XtraReports.Web.DocumentViewer;
    
    #line 1 "..\..\Views\Journal\JournalPartialView.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Journal\JournalPartialView.cshtml"
    using IWSProject.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Journal/JournalPartialView.cshtml")]
    public partial class _Views_Journal_JournalPartialView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Journal_JournalPartialView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Journal\JournalPartialView.cshtml"
Write(Html.DevExpress().GridView(settings =>
{
    settings.Name = "JournalPartialView";
    settings.Caption = IWSLocalResource.journal;

    settings.CallbackRouteValues = new { Controller = "Journal", Action = "JournalPartialView" };

    settings.KeyFieldName = "ItemID";


    settings.SettingsBehavior.AllowSelectByRowClick = true;
    settings.SettingsBehavior.EnableRowHotTrack = true;

    settings.Styles.RowHotTrack.Cursor = "pointer";
    settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.Beige;

    settings.Settings.ShowFilterRow = true;
    settings.Settings.ShowFilterRowMenu = true;
    settings.SettingsBehavior.AllowFocusedRow = true;

    settings.Settings.ShowGroupPanel = true;

    settings.Width = Unit.Percentage(100);
    //settings.Settings.VerticalScrollableHeight = Unit.Percentage(100);
    
    settings.ControlStyle.Paddings.Padding = Unit.Pixel(0);
    settings.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
    settings.ControlStyle.BorderBottom.BorderWidth = Unit.Pixel(1);

    settings.SettingsPager.Visible = true;
    settings.SettingsPager.Position = PagerPosition.Bottom;
    settings.SettingsPager.FirstPageButton.Visible = true;
    settings.SettingsPager.LastPageButton.Visible = true;
    settings.SettingsPager.PageSizeItemSettings.Visible = true;
    
    settings.SettingsPager.PageSize = 24;

    settings.Columns.Add(column =>
    {
        column.FieldName = "ItemID";
        column.Caption = IWSLocalResource.PartNumber;
        column.Width = Unit.Pixel(55);
    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "OID";
        column.Caption = IWSLocalResource.id;
        column.Width = Unit.Pixel(55);
    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "ItemType";
        column.Caption = IWSLocalResource.PartType;
    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "CustSupplierID";
        column.Caption = IWSLocalResource.CustSupplier;
        column.EditorProperties().ComboBox(combo =>
        {
            combo.TextField = "Name";
            combo.ValueField = "id";
            combo.ValueType = typeof(string);
            combo.DataSource = IWSLookUp.GetCustSuppliers();
            combo.Columns.Add("id").Caption = IWSLocalResource.id;
            combo.Columns.Add("name").Caption = IWSLocalResource.CustSupplier;
            combo.TextFormatString = "{0}-{1}";
        });
    });

    settings.Columns.Add(column =>
    {
        column.FieldName = "TransDate";
        column.Caption = IWSLocalResource.duedate;
        column.Width = Unit.Pixel(85);
        column.EditorProperties().TextBox(textBox =>
        {
            textBox.DisplayFormatString = "yyyy-MM-dd";
        });
    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "Periode";
        column.Caption = IWSLocalResource.periode;
        column.Width = Unit.Pixel(55);

    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "Account";
        column.Caption = IWSLocalResource.account;
        column.EditorProperties().ComboBox(combo =>
        {
            combo.TextField = "Name";
            combo.ValueField = "id";
            combo.Width = Unit.Percentage(100);
            combo.ValueType = typeof(string);
            combo.DataSource = IWSLookUp.GetAccounts();
            combo.Columns.Add("id").Caption = IWSLocalResource.id;
            combo.Columns.Add("name").Caption = IWSLocalResource.account;
            combo.TextFormatString = "{0}-{1}";
        });
    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "Side";
        column.Caption = IWSLocalResource.side;
        column.Width = Unit.Pixel(50);
    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "OAccount";
        column.Caption = IWSLocalResource.oaccount;
        column.EditorProperties().ComboBox(combo =>
        {
            combo.TextField = "Name";
            combo.ValueField = "id";
            combo.ValueType = typeof(string);
            combo.DataSource = IWSLookUp.GetAccounts();
            combo.Columns.Add("id").Caption = IWSLocalResource.id;
            combo.Columns.Add("name").Caption = IWSLocalResource.oaccount;
            combo.TextFormatString = "{0}-{1}";
        });
    });

    settings.Columns.Add(column =>
    {
        column.FieldName = "Amount";
        column.Caption = IWSLocalResource.amount;

        column.EditorProperties().TextBox(textBox =>
        {
            textBox.DisplayFormatString = "N";
        });
    });
    settings.Columns.Add(column =>
    {
        column.FieldName = "Currency";
        column.Caption = IWSLocalResource.Currency;
        column.Width = Unit.Pixel(80);
    });

}).Bind(Model).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
