#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 1 "..\..\Views\BankStatements\ImportCSVPartial.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BankStatements/ImportCSVPartial.cshtml")]
    public partial class _Views_BankStatements_ImportCSVPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_BankStatements_ImportCSVPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\BankStatements\ImportCSVPartial.cshtml"
Write(Html.DevExpress().FileManager(settings =>
{
    settings.Name = "FileManager";

    settings.CallbackRouteValues = new { Controller = "BankStatements", Action = "ImportCSVPartial" };

    settings.Settings.AllowedFileExtensions = new string[] { ".csv", ".txt" };
    settings.Settings.EnableMultiSelect = false;

    settings.SettingsEditing.AllowDelete = true;

    settings.SettingsUpload.Enabled = true;
    settings.SettingsEditing.AllowDownload = true;
    settings.SettingsUpload.UseAdvancedUploadMode = true;
    settings.SettingsUpload.AdvancedModeSettings.EnableMultiSelect = true;

    settings.ClientSideEvents.CustomCommand = "OnCustomCommand";
    settings.ClientSideEvents.ToolbarUpdating = "OnToolbarUpdating";

    settings.SettingsContextMenu.Items.Add(new FileManagerToolbarDeleteButton());
    settings.SettingsToolbar.Items.Add(new FileManagerToolbarDeleteButton());

    settings.SettingsContextMenu.Items.Add(new FileManagerToolbarRefreshButton());
    settings.SettingsToolbar.Items.Add(new FileManagerToolbarRefreshButton());

    var uploadToDBButton = new FileManagerToolbarCustomButton();
    uploadToDBButton.CommandName = "UploadToDB";
    uploadToDBButton.Text = IWSLocalResource.UploadToDB;
    uploadToDBButton.Image.IconID = IconID.ActionsUp216x16;
    uploadToDBButton.BeginGroup = true;

    settings.SettingsContextMenu.Items.Add(uploadToDBButton);
    settings.SettingsContextMenu.Enabled = true;

    uploadToDBButton = new FileManagerToolbarCustomButton();
    uploadToDBButton.CommandName = "UploadToDB";
    uploadToDBButton.ToolTip = IWSLocalResource.UploadToDB;
    uploadToDBButton.Image.IconID = IconID.ActionsUp216x16;
    uploadToDBButton.BeginGroup = true;

    settings.SettingsToolbar.Items.Add(uploadToDBButton);

    settings.SettingsUpload.NullText = (string)ViewData["GenericError"];

    settings.SettingsUpload.NullText = IWSLocalResource.DropFiles;

    settings.SettingsUpload.AdvancedModeSettings.DropZoneText = (string)ViewData["GenericError"];

}).BindToFolder(Model).GetHtml());

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
