#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BankStatements/ImportCSV.cshtml")]
    public partial class _Views_BankStatements_ImportCSV_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_BankStatements_ImportCSV_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

    function OnCustomCommand(s, e) {
        if (e.commandName == ""UploadToDB"") {
            var items = FileManager.GetSelectedItems();
            var names = [];

            for (var i = 0; i < items.length; i++) {
                names[i] = items[i].GetFullName();
            }
            $.ajax({
                url: '");

            
            #line 12 "..\..\Views\BankStatements\ImportCSV.cshtml"
                 Write(Url.Action("UploadToDB", "BankStatements"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                type: ""POST"",
                dataType: ""json"",
                data: { files: names },
                success: function (Message) {
                    alert(Message.Description);
                }
            })
        }
        }
        function OnToolbarUpdating(s, e) {
            var enabled = (FileManager.GetSelectedItems().length > 0) &&
                                        e.activeAreaName != ""None"";
            FileManager.GetToolbarItemByCommandName(""UploadToDB"").SetEnabled(enabled);

            FileManager.GetContextMenuItemByCommandName(""UploadToDB"").SetEnabled(enabled);
        }                
</script>

");

            
            #line 31 "..\..\Views\BankStatements\ImportCSV.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\BankStatements\ImportCSV.cshtml"
Write(Html.Action("ImportCSVPartial"));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\BankStatements\ImportCSV.cshtml"
                                    
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
