#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 1 "..\..\Views\BankStatements\Index.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BankStatements/Index.cshtml")]
    public partial class _Views_BankStatements_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_BankStatements_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    var selectedIDs;

    function onButtonClick() {
        if (BankStatementsGridView.IsCustomizationWindowVisible())
            BankStatementsGridView.HideCustomizationWindow();
        else
            BankStatementsGridView.ShowCustomizationWindow();
        UpdateButtonText();
    }
    function CustomizationWindowCloseUp(s, e) {
        UpdateButtonText();
    }
    function UpdateButtonText() {
        var text = BankStatementsGridView.IsCustomizationWindowVisible() ? ""Hide"" : ""Show"";
        text += "" Customization"";
        btShowCustomizationWindow.SetText(text);
    }

    function OnBeginCallback(s, e) {
        e.customArgs[""selectedIDs""] = selectedIDs;
    }
    function OnSelectionChanged(s, e) {
        s.GetSelectedFieldValues(""id;Betrag"", GetSelectedFieldValuesCallback);
    }
    function GetSelectedFieldValuesCallback(values) {
        selectedIDs = values.join(';');
    }
    function OnSubmitClick(s, e) {
        $(""#selectedIDsHF"").val(selectedIDs);
    }

</script>

");

            
            #line 36 "..\..\Views\BankStatements\Index.cshtml"
 using (Html.BeginForm("Index", "BankStatements"))
{
    
            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\BankStatements\Index.cshtml"
Write(Html.Hidden("selectedIDsHF"));

            
            #line default
            #line hidden
            
            #line 38 "..\..\Views\BankStatements\Index.cshtml"
                                 ;

    
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\BankStatements\Index.cshtml"
Write(Html.DevExpress().Button(settings =>
{
    settings.Name = "btnSubmit";
    settings.Text = IWSLocalResource.Validate;
    settings.Width = Unit.Pixel(150);
    settings.UseSubmitBehavior = true;
    settings.ClientSideEvents.Click = "OnSubmitClick";
}).GetHtml());

            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\BankStatements\Index.cshtml"
            

    
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\BankStatements\Index.cshtml"
Write(Html.DevExpress().Button(settings =>   
{
    settings.Name = "btShowCustomizationWindow";
    settings.UseSubmitBehavior = false;
    settings.Text = IWSLocalResource.WindowCustomization;
    settings.ClientSideEvents.Click = "onButtonClick";
}).GetHtml());

            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\BankStatements\Index.cshtml"
            
}

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\BankStatements\Index.cshtml"
Write(Html.Action("BankStatementsGridViewPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
