#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePasswordSuccess.cshtml")]
    public partial class _Views_Account_ChangePasswordSuccess_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_ChangePasswordSuccess_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"accountHeader\"");

WriteLiteral(">\r\n    <h2>Change Password</h2>\r\n    <p>Your password has been changed successful" +
"ly.</p>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
