#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ExternalLoginConfirmation.cshtml")]
    public partial class _Views_Account_ExternalLoginConfirmation_cshtml : System.Web.Mvc.WebViewPage<IWSProject.Models.ExternalLoginConfirmationViewModel>
    {
        public _Views_Account_ExternalLoginConfirmation_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
  
    ViewBag.Title = "Register";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"accountHeader\"");

WriteLiteral(">\r\n    <h2>Associate your ");

            
            #line 8 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                  Write(ViewBag.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral(" account</h2>\r\n</div>\r\n");

            
            #line 10 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
 using (Html.BeginForm("ExternalLoginConfirmation", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
{
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        You\'ve successfully authenticated with <strong>");

            
            #line 15 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                                                  Write(ViewBag.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n        Please enter an email for this site below and click the Regis" +
"ter button to finish\r\n        logging in.\r\n    </p>\r\n");

            
            #line 19 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.DevExpress().TextBoxFor(m => m.Email, s => {
        s.Properties.Caption = "Email";
        s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
        s.ShowModelErrors = true;
        s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");

            
            #line 26 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.DevExpress().Button(s => {
        s.Name = "Register";
        s.Text = "Register";
        s.UseSubmitBehavior = true;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
