#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/SendCode.cshtml")]
    public partial class _Views_Account_SendCode_cshtml : System.Web.Mvc.WebViewPage<IWSProject.Models.SendCodeViewModel>
    {
        public _Views_Account_SendCode_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\SendCode.cshtml"
  
    ViewBag.Title = "Send Code";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"accountHeader\"");

WriteLiteral(">\r\n    <h2>");

            
            #line 6 "..\..\Views\Account\SendCode.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n</div>\r\n");

            
            #line 8 "..\..\Views\Account\SendCode.cshtml"
 using (Html.BeginForm("SendCode", "Account", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post)) {

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\SendCode.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\SendCode.cshtml"
                        
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\SendCode.cshtml"
Write(Html.Hidden("rememberMe", Model.RememberMe));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\SendCode.cshtml"
                                                

            
            #line default
            #line hidden
WriteLiteral("    <h4>Send verification code</h4>\r\n");

            
            #line 12 "..\..\Views\Account\SendCode.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\SendCode.cshtml"
Write(Html.DevExpress().ComboBoxFor(m=>m.SelectedProvider, s=>{
        s.Properties.Caption = "Select Two-Factor Authentication Provider";
        s.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
        s.SelectedIndex = 0;
    }).BindList(Model.Providers).GetHtml());

            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Account\SendCode.cshtml"
                                          

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");

            
            #line 18 "..\..\Views\Account\SendCode.cshtml"
    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\SendCode.cshtml"
Write(Html.DevExpress().Button(s => {
        s.Name = s.Text = "Submit";
        s.UseSubmitBehavior = true;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Account\SendCode.cshtml"
                
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
