//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IWSProject.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IWSLocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IWSLocalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IWSProject.Content.IWSLocalResource", typeof(IWSLocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance.
        /// </summary>
        public static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account ID.
        /// </summary>
        public static string accountid {
            get {
                return ResourceManager.GetString("accountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Method.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Assignement.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string administration {
            get {
                return ResourceManager.GetString("administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string articles {
            get {
                return ResourceManager.GetString("articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Price.
        /// </summary>
        public static string AveragePrice {
            get {
                return ResourceManager.GetString("AveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string bankaccount {
            get {
                return ResourceManager.GetString("bankaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string bankaccountid {
            get {
                return ResourceManager.GetString("bankaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        public static string banks {
            get {
                return ResourceManager.GetString("banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIC.
        /// </summary>
        public static string bic {
            get {
                return ResourceManager.GetString("bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string btnAddNew {
            get {
                return ResourceManager.GetString("btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string controller {
            get {
                return ResourceManager.GetString("controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string costcenters {
            get {
                return ResourceManager.GetString("costcenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curent Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string dateofclose {
            get {
                return ResourceManager.GetString("dateofclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Date.
        /// </summary>
        public static string dateofopen {
            get {
                return ResourceManager.GetString("dateofopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        public static string debit {
            get {
                return ResourceManager.GetString("debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string duedate {
            get {
                return ResourceManager.GetString("duedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expensive Account.
        /// </summary>
        public static string expenseaccountid {
            get {
                return ResourceManager.GetString("expenseaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Receiving.
        /// </summary>
        public static string GoodReceiving {
            get {
                return ResourceManager.GetString("GoodReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID.
        /// </summary>
        public static string groupid {
            get {
                return ResourceManager.GetString("groupid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input VAT Account.
        /// </summary>
        public static string inputvataccountid {
            get {
                return ResourceManager.GetString("inputvataccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Invoice.
        /// </summary>
        public static string InventoryInvoice {
            get {
                return ResourceManager.GetString("InventoryInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsValidated.
        /// </summary>
        public static string IsValidated {
            get {
                return ResourceManager.GetString("IsValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item #.
        /// </summary>
        public static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Good Receiving.
        /// </summary>
        public static string LineGoodReceiving {
            get {
                return ResourceManager.GetString("LineGoodReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Inventory Invoice.
        /// </summary>
        public static string LineInventoryInvoice {
            get {
                return ResourceManager.GetString("LineInventoryInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Payment.
        /// </summary>
        public static string linepayment {
            get {
                return ResourceManager.GetString("linepayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Purchase Order.
        /// </summary>
        public static string lineprchaseorder {
            get {
                return ResourceManager.GetString("lineprchaseorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Vendor Invoice.
        /// </summary>
        public static string linevendorinvoice {
            get {
                return ResourceManager.GetString("linevendorinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string manage {
            get {
                return ResourceManager.GetString("manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Files.
        /// </summary>
        public static string masterfiles {
            get {
                return ResourceManager.GetString("masterfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Order.
        /// </summary>
        public static string menuorder {
            get {
                return ResourceManager.GetString("menuorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Management.
        /// </summary>
        public static string menus {
            get {
                return ResourceManager.GetString("menus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Stock.
        /// </summary>
        public static string minstock {
            get {
                return ResourceManager.GetString("minstock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ID.
        /// </summary>
        public static string modelid {
            get {
                return ResourceManager.GetString("modelid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Account.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Period.
        /// </summary>
        public static string nextperiode {
            get {
                return ResourceManager.GetString("nextperiode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAccount.
        /// </summary>
        public static string oaccount {
            get {
                return ResourceManager.GetString("oaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OID.
        /// </summary>
        public static string oid {
            get {
                return ResourceManager.GetString("oid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output VAT Account.
        /// </summary>
        public static string outputvataccountid {
            get {
                return ResourceManager.GetString("outputvataccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Unit.
        /// </summary>
        public static string packunit {
            get {
                return ResourceManager.GetString("packunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Parent.
        /// </summary>
        public static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Clearing Account.
        /// </summary>
        public static string paymentclearingaccountid {
            get {
                return ResourceManager.GetString("paymentclearingaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periode.
        /// </summary>
        public static string periode {
            get {
                return ResourceManager.GetString("periode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing.
        /// </summary>
        public static string purchasing {
            get {
                return ResourceManager.GetString("purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchasing Clearing Account.
        /// </summary>
        public static string purchasingclearingaccountid {
            get {
                return ResourceManager.GetString("purchasingclearingaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string qttyunit {
            get {
                return ResourceManager.GetString("qttyunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantiy.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Unit.
        /// </summary>
        public static string quantityunit {
            get {
                return ResourceManager.GetString("quantityunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Account.
        /// </summary>
        public static string revenueaccountid {
            get {
                return ResourceManager.GetString("revenueaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        public static string RoleManagement1 {
            get {
                return ResourceManager.GetString("RoleManagement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Assignement.
        /// </summary>
        public static string RolesAssignement {
            get {
                return ResourceManager.GetString("RolesAssignement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        public static string rolesmanagement {
            get {
                return ResourceManager.GetString("rolesmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Clearing Account.
        /// </summary>
        public static string salesclearingaccountid {
            get {
                return ResourceManager.GetString("salesclearingaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price.
        /// </summary>
        public static string salesprice {
            get {
                return ResourceManager.GetString("salesprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement Clearing Account.
        /// </summary>
        public static string settlementclearingaccountid {
            get {
                return ResourceManager.GetString("settlementclearingaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string side {
            get {
                return ResourceManager.GetString("side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Account.
        /// </summary>
        public static string stockaccountid {
            get {
                return ResourceManager.GetString("stockaccountid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string supplier {
            get {
                return ResourceManager.GetString("supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string taxcode {
            get {
                return ResourceManager.GetString("taxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string transid {
            get {
                return ResourceManager.GetString("transid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Credential.
        /// </summary>
        public static string UserCredential {
            get {
                return ResourceManager.GetString("UserCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string usersmanagement {
            get {
                return ResourceManager.GetString("usersmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Management.
        /// </summary>
        public static string UsersManagement1 {
            get {
                return ResourceManager.GetString("UsersManagement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string vat {
            get {
                return ResourceManager.GetString("vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Code.
        /// </summary>
        public static string vatcode {
            get {
                return ResourceManager.GetString("vatcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Invoice.
        /// </summary>
        public static string vendorinvoice {
            get {
                return ResourceManager.GetString("vendorinvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Code.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
