#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 2 "..\..\Views\Accounting\Index.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Accounting\Index.cshtml"
    using IWSProject.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Accounting/Index.cshtml")]
    public partial class _Views_Accounting_Index_cshtml : System.Web.Mvc.WebViewPage<List<DocumentsViewModel>>
    {
        public _Views_Accounting_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var selectedIDs;
        function OnBeginCallback(s, e) {
            ///passes selected row data to GridView callback action
            e.customArgs[""selectedIDs""] = selectedIDs;
        }
        function OnSelectionChanged(s, e) {
            s.GetSelectedFieldValues(""ItemID;ItemType"", GetSelectedFieldValuesCallback);
        }
        function GetSelectedFieldValuesCallback(values) {
            //joins selected keys
            selectedIDs = values.join(';');
        }
        function OnSubmitClick(s, e) {
            //collects selected row data to hidden input then throw it to post action
            $(""#selectedIDsHF"").val(selectedIDs);
        }
    </script>

");

            
            #line 23 "..\..\Views\Accounting\Index.cshtml"
 using (Html.BeginForm("Index", "Accounting"))
{
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Accounting\Index.cshtml"
Write(Html.Hidden("selectedIDsHF"));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Accounting\Index.cshtml"
                                 ;
    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Accounting\Index.cshtml"
Write(Html.DevExpress().Button(settings =>
{
    settings.Name = "btnSubmit";
    settings.Text = IWSLocalResource.Validate;
    settings.Width = Unit.Pixel(150);
    settings.UseSubmitBehavior = true;
    settings.ClientSideEvents.Click = "OnSubmitClick";
}).GetHtml());

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Accounting\Index.cshtml"
            
}

            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Accounting\Index.cshtml"
Write(Html.Partial("ValidateBLPartialView", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
