#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 1 "..\..\Views\Accounting\ValidateBLPartialView.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Accounting\ValidateBLPartialView.cshtml"
    using IWSProject.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Accounting/ValidateBLPartialView.cshtml")]
    public partial class _Views_Accounting_ValidateBLPartialView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Accounting_ValidateBLPartialView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Accounting\ValidateBLPartialView.cshtml"
  
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "ValidateBLGridView";
        settings.Caption = IWSLocalResource.Accounting;

        settings.CallbackRouteValues = new { Controller = "Accounting", Action = "ValidateBLPartialView" };

        settings.KeyFieldName = "ItemID;ItemType";

        settings.Settings.ShowFilterRow = true;
        settings.Settings.ShowFilterRowMenu = true;

        settings.Settings.ShowGroupPanel = true;
        settings.SettingsBehavior.AllowFocusedRow = true;

        settings.CommandColumn.Visible = true;
        settings.CommandColumn.Width = Unit.Pixel(85);
        settings.CommandColumn.ShowSelectCheckbox = true;

        settings.Width = Unit.Percentage(100);

        settings.Settings.VerticalScrollBarMode = ScrollBarMode.Hidden;
        settings.Settings.VerticalScrollableHeight = 350;
        settings.ControlStyle.Paddings.Padding = Unit.Pixel(0);
        settings.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
        settings.ControlStyle.BorderBottom.BorderWidth = Unit.Pixel(1);
        settings.ClientSideEvents.SelectionChanged = "OnSelectionChanged";
        settings.ClientSideEvents.BeginCallback = "OnBeginCallback";

        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.SettingsBehavior.EnableRowHotTrack = true;

        settings.Styles.RowHotTrack.Cursor = "pointer";
        settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.Beige;

        settings.SettingsPager.Visible = true;
        settings.SettingsPager.Position = PagerPosition.Bottom;
        settings.SettingsPager.FirstPageButton.Visible = true;
        settings.SettingsPager.LastPageButton.Visible = true;
        settings.SettingsPager.PageSizeItemSettings.Visible = true;
        settings.SettingsPager.PageSizeItemSettings.Items = new string[] { "24", "30", "36", "50" };
        settings.SettingsPager.PageSize = 24;

        settings.Columns.Add(column =>
        {
            column.FieldName = "ItemID";
            column.Caption = IWSLocalResource.PartNumber;
            column.Width = Unit.Pixel(85);
        });
        settings.Columns.Add(column =>
        {
            column.FieldName = "ItemType";
            column.Caption = IWSLocalResource.PartType;
            column.Width = Unit.Pixel(200);
        });
        settings.Columns.Add(column =>
        {
            column.FieldName = "DueDate";
            column.Caption = IWSLocalResource.duedate;
            column.Width = Unit.Pixel(85);
            column.EditorProperties().TextBox(textBox =>
            {
                textBox.DisplayFormatString = "yyyy-MM-dd";
            });
        });
        settings.Columns.Add(column =>
        {
            column.FieldName = "SupplierID";
            column.Caption = IWSLocalResource.CustSupplier;
            column.EditorProperties().ComboBox(combo =>
            {
                combo.TextField = "Name";
                combo.ValueField = "id";
                combo.ValueType = typeof(string);
                combo.DataSource = IWSLookUp.GetCustSuppliers();
                combo.Columns.Add("id").Caption = IWSLocalResource.id;
                combo.Columns.Add("name").Caption = IWSLocalResource.CustSupplier;
                combo.TextFormatString = "{0}-{1}";
            });
        });

        settings.Columns.Add(column =>
        {
            column.FieldName = "CompanyID";
            column.Caption = IWSLocalResource.company;
            column.EditorProperties().ComboBox(combo =>
            {
                combo.TextField = "Name";
                combo.ValueField = "id";
                combo.ValueType = typeof(string);
                combo.DataSource = IWSLookUp.GetCompanies();
                combo.Columns.Add("id").Caption = IWSLocalResource.id;
                combo.Columns.Add("name").Caption = IWSLocalResource.company;
                combo.TextFormatString = "{0}-{1}";
            });
        });

        settings.Columns.Add(column =>
        {
            column.FieldName = "TotalHVAT";
            column.Caption = IWSLocalResource.TotHVAT;
            column.Width = Unit.Pixel(120);
            column.EditorProperties().TextBox(textBox =>
            {
                textBox.DisplayFormatString = "c";
            });
        });

        settings.Columns.Add(column =>
        {
            column.FieldName = "TotalVAT";
            column.Caption = IWSLocalResource.TotVAT;
            column.Width = Unit.Pixel(120);
            column.EditorProperties().TextBox(textBox =>
            {
                textBox.DisplayFormatString = "c";
            });
        });
    });
    if (ViewData["GenericError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["GenericError"]);
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 128 "..\..\Views\Accounting\ValidateBLPartialView.cshtml"
Write(grid.Bind(Model).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
