#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/ListBoxPartial.cshtml")]
    public partial class _Views_Home_ListBoxPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_ListBoxPartial_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\ListBoxPartial.cshtml"
Write(Html.DevExpress().ListBox(
    settings =>
    {
        settings.Name = "lbModels";
        settings.CallbackRouteValues = new { Controller = "Editors", Action = "ListBoxPartial" };
        settings.Width = 300;
        settings.Height = 210;
        settings.Properties.Caption = "Accepted models:";
        settings.Properties.CaptionSettings.Position = EditorCaptionPosition.Top;
        settings.Properties.EnableClientSideAPI = true;
        settings.Properties.ValueField = "ID";
        settings.Properties.ValueType = typeof(string);
        settings.Properties.Columns.Add("Name", "Model").Width = Unit.Percentage(100);
        settings.Properties.Columns.Add("Price").Width = 50;
    }
).BindList(Model).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
