#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_mainLayout.cshtml")]
    public partial class _Views_Shared__mainLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__mainLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Shared\_mainLayout.cshtml"
   Layout = "~/Views/Shared/_rootLayout.cshtml"; 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 4 "..\..\Views\Shared\_mainLayout.cshtml"
Write(Html.DevExpress().Splitter(settings =>
{
    settings.Name = "ContentSplitter";
    settings.Width = Unit.Percentage(100);
    settings.Height = Unit.Percentage(100);
    settings.Styles.Pane.Paddings.Padding = Unit.Pixel(0);
    settings.Styles.Pane.Border.BorderWidth = Unit.Pixel(0);
    settings.ClientSideEvents.PaneResized = "function(s, e) { if(window.GridView && e.pane.name == 'ContentCenter') GridView.SetHeight(e.pane.GetClientHeight()); }";
    settings.Panes.Add(subpane =>
    {
        subpane.Name = "ContentLeft";
        subpane.PaneStyle.CssClass = "leftPane";
        subpane.ShowCollapseBackwardButton = DefaultBoolean.False;
        subpane.Size = Unit.Pixel(200);
        subpane.MinSize = Unit.Pixel(150);
        subpane.PaneStyle.Paddings.Padding = Unit.Pixel(1);
        subpane.SetContent(() =>
        {
            Html.RenderPartial("ContentLeftPartialView");
        });
    });

    settings.Panes.Add(subpane =>
    {
        subpane.Name = "ContentCenter";
        subpane.PaneStyle.CssClass = "contentPane";
        subpane.ScrollBars = ScrollBars.Auto;
        subpane.Separator.Visible = DefaultBoolean.True;
        subpane.Separator.SeparatorStyle.Border.BorderWidth = Unit.Pixel(1);
        subpane.Separator.SeparatorStyle.BorderTop.BorderWidth = Unit.Pixel(0);
        subpane.SetContent(RenderBody().ToHtmlString());
    });

}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
