#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    using DevExpress.XtraReports;
    using DevExpress.XtraReports.UI;
    using DevExpress.XtraReports.Web;
    using DevExpress.XtraReports.Web.DocumentViewer;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_rootLayout.cshtml")]
    public partial class _Views_Shared__rootLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__rootLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"UTF-8\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 7 "..\..\Views\Shared\_rootLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 111), Tuple.Create("\"", 152)
            
            #line 8 "..\..\Views\Shared\_rootLayout.cshtml"
, Tuple.Create(Tuple.Create("", 118), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/Site.css")
            
            #line default
            #line hidden
, 118), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n   \r\n");

            
            #line 10 "..\..\Views\Shared\_rootLayout.cshtml"
Write(Html.DevExpress().GetStyleSheets(
    new StyleSheet { ExtensionSuite = ExtensionSuite.Report },
    new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new StyleSheet { ExtensionSuite = ExtensionSuite.GridView },
    new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
    new StyleSheet { ExtensionType = ExtensionType.WebDocumentViewer }
    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 17 "..\..\Views\Shared\_rootLayout.cshtml"
Write(Html.DevExpress().GetScripts(
    new Script { ExtensionSuite = ExtensionSuite.Report },
    new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
    new Script { ExtensionSuite = ExtensionSuite.GridView },
    new Script { ExtensionSuite = ExtensionSuite.Editors },
    new Script { ExtensionType = ExtensionType.WebDocumentViewer }
    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Shared\_rootLayout.cshtml"
Write(Html.DevExpress().Splitter(settings => {
    settings.Name = "MainSplitter";
    settings.AllowResize = false;
    settings.Orientation = Orientation.Vertical;
    settings.FullscreenMode = true;
    settings.SeparatorVisible = false;
    settings.Styles.Pane.Border.BorderWidth = Unit.Pixel(0);
    settings.Styles.Pane.Paddings.Padding = Unit.Pixel(0);

    settings.Panes.Add(pane => {
        pane.Name = "Header";
        pane.AutoHeight = true;
        pane.PaneStyle.BorderBottom.BorderWidth = Unit.Pixel(1);
        pane.PaneStyle.CssClass = "headerPane";
            pane.SetContent(() => {
                Html.RenderPartial("HeaderPartialView");
            });
    });

    settings.Panes.Add(pane => {
        pane.Name = "Content";
        pane.PaneStyle.CssClass = "mainContentPane";
        pane.MinSize = Unit.Pixel(375);
        pane.PaneStyle.BackColor = System.Drawing.Color.White;
        pane.PaneStyle.BorderBottom.BorderWidth = Unit.Pixel(1);
        pane.SetContent(RenderBody().ToHtmlString());
    });

}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
