#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 4 "..\..\Views\Shared\ContentLeftPartialView.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    
    #line 3 "..\..\Views\Shared\ContentLeftPartialView.cshtml"
    using System.Resources;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 1 "..\..\Views\Shared\ContentLeftPartialView.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\ContentLeftPartialView.cshtml"
    using IWSProject.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/ContentLeftPartialView.cshtml")]
    public partial class _Views_Shared_ContentLeftPartialView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_ContentLeftPartialView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\ContentLeftPartialView.cshtml"
  
        List<IWSProject.Models.Menu> menuItems = new List<IWSProject.Models.Menu>();
        if (HttpContext.Current.Session["Menus"] != null)
        {
            menuItems = (List<IWSProject.Models.Menu>)HttpContext.Current.Session["Menus"];
        } 
            
            #line default
            #line hidden
WriteLiteral("\r\n \r\n");

WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\Shared\ContentLeftPartialView.cshtml"
Write(Html.DevExpress().NavBar(settings =>
{
    settings.Name = "navBarMenu";
    settings.AutoCollapse = true;
    settings.EnableAnimation = true;
    settings.Width = Unit.Percentage(100);
    settings.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
    settings.ControlStyle.Paddings.Padding = Unit.Pixel(0);
    ResourceManager rm = new ResourceManager(typeof(IWSLocalResource));
    if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        //get current user
        var user = HttpContext.Current.User.Identity.Name;
        //find current user assigned roles
        string[] roles = Roles.GetRolesForUser(user);
        //retrieve corrsponding menu items
        var menus = from item in menuItems
                    where item.Roles.Split(new String[] { "," }, StringSplitOptions.RemoveEmptyEntries)
                    .Any(x => roles.Contains(x) || x == "All")
                    select item;
        //build the action links
        foreach (var link in menuItems.Where(p => (p.Parent == 0) && (p.HasAccess == false)).OrderBy(o=>o.MenuOrder))
        {
            settings.Groups.Add(group =>
            {
                group.Name = link.Name;
                group.Text = rm.GetString(link.Name);

                foreach (var mc in menus.Where(c => c.Parent == link.ID).OrderBy(o=>o.MenuOrder))
                {
                    group.Items.Add(item =>
                    {
                        item.Name = mc.Name;
                        item.Text = rm.GetString(mc.Name);
                        item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = mc.Controller, Action = mc.Action });
                    });
                }
            });
        }
    }
    else
    {
        var menus = from item in menuItems
                    where item.Roles.Split(new String[] { "," }, StringSplitOptions.RemoveEmptyEntries)
                    .Any(x => new String[] { "All" }.Contains(x))
                    select item;
        //build the action links
        foreach (var link in menus.Where(p => (p.Parent == 0) && (p.HasAccess == false)))
        {
            settings.Groups.Add(group =>
            {
                group.Name = link.Name;
                group.Text = rm.GetString(link.Name);
                foreach (var mc in menus.Where(c => c.Parent == link.ID))
                {
                    group.Items.Add(item =>
                    {
                        item.Name = mc.Name;
                        item.Text = rm.GetString(mc.Name);
                        item.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = mc.Controller, Action = mc.Action });
                    });
                }
            });
        }
    }
    
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
