#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    #line 4 "..\..\Views\Shared\HeaderMenuPartialView.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Net;
    
    #line 3 "..\..\Views\Shared\HeaderMenuPartialView.cshtml"
    using System.Resources;
    
    #line default
    #line hidden
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 1 "..\..\Views\Shared\HeaderMenuPartialView.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\HeaderMenuPartialView.cshtml"
    using IWSProject.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/HeaderMenuPartialView.cshtml")]
    public partial class _Views_Shared_HeaderMenuPartialView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_HeaderMenuPartialView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\HeaderMenuPartialView.cshtml"
  
        List<IWSProject.Models.Menu> menuItems = new List<IWSProject.Models.Menu>();
        if (HttpContext.Current.Session["Menus"] != null)
        {
            menuItems = (List<IWSProject.Models.Menu>)HttpContext.Current.Session["Menus"];
        } 
            
            #line default
            #line hidden
WriteLiteral("\r\n \r\n");

WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\Shared\HeaderMenuPartialView.cshtml"
Write(Html.DevExpress().Menu(settings =>
{
    settings.Name = "HeaderMenu";
    settings.ItemAutoWidth = false;
    settings.Width = Unit.Percentage(100);
    settings.Styles.Style.Border.BorderWidth = Unit.Pixel(0);
    settings.Styles.Style.BorderTop.BorderWidth = Unit.Pixel(1);

    ResourceManager rm = new ResourceManager(typeof(IWSLocalResource));
    if(HttpContext.Current.User.Identity.IsAuthenticated)
    {
        //get current user
        var user = HttpContext.Current.User.Identity.Name;
        //find current user assigned roles
        string[] roles = Roles.GetRolesForUser(user);
        //retrieve corrsponding menu items
        var links = from item in menuItems
                    where item.Roles.Split(new String[] { "," }, StringSplitOptions.RemoveEmptyEntries)
                    .Any(x => roles.Contains(x) || x == "All") && item.HasAccess==true
                    select item;
        //build the action links
        foreach (var link in links)
        {
            settings.Items.Add(items =>
            {
                 items.Name = link.Name;
                 items.Text = rm.GetString(link.Name);
                 items.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = link.Controller, Action = link.Action });
            });
        }
    }
    else
    {
        var links = from item in menuItems
                    where item.Roles.Split(new String[] { "," }, StringSplitOptions.RemoveEmptyEntries)
                    .Any(x => new String[] { "All", "Anonymous" }.Contains(x)) && item.HasAccess==true
                    select item;
        foreach (var link in links)
        {
            settings.Items.Add(items =>
            {
                items.Name = link.Name;
                items.Text = rm.GetString(link.Name);
                items.NavigateUrl = DevExpressHelper.GetUrl(new { Controller = link.Controller, Action = link.Action });
            });
        }
    }
}).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
