#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/LogOnPartialView.cshtml")]
    public partial class _Views_Shared_LogOnPartialView_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_LogOnPartialView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    function Init(s, e) {
        s.SetValue(ASPxClientUtils.GetCookie(""Culture""));
    }
    function SelectedIndexChanged(s) {
        ASPxClientUtils.SetCookie(""Culture"", s.GetValue());
        //alert(s.GetValue());
        $(""#form"").submit();
    }
</script>

");

            
            #line 12 "..\..\Views\Shared\LogOnPartialView.cshtml"
 if(!Request.IsAuthenticated) {
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Shared\LogOnPartialView.cshtml"
Write(Html.ActionLink("Register", "Register", "Account"));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Shared\LogOnPartialView.cshtml"
                                                        

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral(" | \r\n");

            
            #line 15 "..\..\Views\Shared\LogOnPartialView.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\LogOnPartialView.cshtml"
Write(Html.ActionLink("Login", "Login", "Account"));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\LogOnPartialView.cshtml"
                                                 
}
else {
 

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral(" Welcome ");

            
            #line 19 "..\..\Views\Shared\LogOnPartialView.cshtml"
          Write(Html.ActionLink(User.Identity.Name + "!", "ChangePassword", "Account", routeValues: null, htmlAttributes: new { title = "Manage" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

WriteLiteral(" |\r\n");

            
            #line 21 "..\..\Views\Shared\LogOnPartialView.cshtml"
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\LogOnPartialView.cshtml"
Write(Html.ActionLink("Logout", "LogOff", "Account"));

            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\LogOnPartialView.cshtml"
                                                   
}

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\LogOnPartialView.cshtml"
 using (Html.BeginForm(null, null, FormMethod.Post, new { id = "form" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"uiCulture\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\Shared\LogOnPartialView.cshtml"
   Write(Html.DevExpress().ComboBox(
            settings =>
            {
                settings.Name = "SelectCulture";
                settings.Width = Unit.Pixel(75);
                settings.SelectedIndex = 0;
                settings.Properties.ValueType = typeof(string);
                settings.Properties.Items.Add("Deutsch", "de-DE");
                settings.Properties.Items.Add("English", "en-US");
                settings.Properties.Items.Add("Espa�ol", "es-ES");
                settings.Properties.Items.Add("Fran�ais", "fr-FR");
                settings.Properties.ClientSideEvents.SelectedIndexChanged = "SelectedIndexChanged";
                settings.Properties.ClientSideEvents.Init = "Init";
            }
        ).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 42 "..\..\Views\Shared\LogOnPartialView.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral(" ");

        }
    }
}
#pragma warning restore 1591
