#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ForgotPassword.cshtml")]
    public partial class _Views_Account_ForgotPassword_cshtml : System.Web.Mvc.WebViewPage<IWSProject.Models.ForgotPasswordViewModel>
    {
        public _Views_Account_ForgotPassword_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 3 "..\..\Views\Account\ForgotPassword.cshtml"
  
    ViewBag.Title = "Forgot password";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"accountHeader\"");

WriteLiteral(">\r\n    <h2>");

            
            #line 7 "..\..\Views\Account\ForgotPassword.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n</div>\r\n");

            
            #line 9 "..\..\Views\Account\ForgotPassword.cshtml"
 using (Html.BeginForm("ForgotPassword", "Account", FormMethod.Post))
{
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\ForgotPassword.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\ForgotPassword.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <h4>Enter your email.</h4>\r\n");

            
            #line 13 "..\..\Views\Account\ForgotPassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ForgotPassword.cshtml"
Write(Html.DevExpress().TextBoxFor(m => m.Email, s => {
        s.Properties.Caption = "Email";
        s.ShowModelErrors = true;
        s.Properties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.ImageWithText;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\ForgotPassword.cshtml"
                

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");

            
            #line 19 "..\..\Views\Account\ForgotPassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Account\ForgotPassword.cshtml"
Write(Html.DevExpress().Button(s => {
        s.Name = "EmailLink";
        s.Text = "Email Link";
        s.UseSubmitBehavior = true;
    }).GetHtml());

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Account\ForgotPassword.cshtml"
                
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
