#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 2 "..\..\Views\Account\UsersList.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Account\UsersList.cshtml"
    using IWSProject.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/UsersList.cshtml")]
    public partial class _Views_Account_UsersList_cshtml : System.Web.Mvc.WebViewPage<List<EditUserViewModel>>
    {
        public _Views_Account_UsersList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Account\UsersList.cshtml"
  
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "UsersGridView";
        settings.Caption = IWSLocalResource.RolesAssignement;

        settings.CallbackRouteValues = new { Controller = "Account", Action = "UsersList" };

        settings.KeyFieldName = "UserName";

        settings.Settings.ShowGroupPanel = true;
        settings.SettingsBehavior.AllowFocusedRow = true;

        settings.Settings.ShowFilterRow = true;
        settings.Settings.ShowFilterRowMenu = true;

        settings.Width = Unit.Percentage(100);
        settings.SettingsPager.PageSize = 24;
        
        
        settings.ControlStyle.Paddings.Padding = Unit.Pixel(0);
        settings.ControlStyle.Border.BorderWidth = Unit.Pixel(0);
        settings.ControlStyle.BorderBottom.BorderWidth = Unit.Pixel(1);

        settings.SettingsPager.Visible = true;
        settings.SettingsPager.Position = PagerPosition.Bottom;
        settings.SettingsPager.FirstPageButton.Visible = true;
        settings.SettingsPager.LastPageButton.Visible = true;
        settings.SettingsPager.PageSizeItemSettings.Visible = true;
        
        settings.SettingsPager.PageSize = 24;

        settings.ClientSideEvents.RowClick =
                                   string.Format("function(s, e) {{ OnRowClicked(s, e, '{0}'); }}",
                                   Url.Action("UserRoles"));

        settings.Columns.Add("FirstName").Caption = IWSLocalResource.FirstName;
        settings.Columns.Add("LastName").Caption = IWSLocalResource.LastName;
        settings.Columns.Add("UserName").Caption = IWSLocalResource.User;
        settings.Columns.Add("Email").Caption = IWSLocalResource.Email;
        settings.Columns.Add("Company").Caption = IWSLocalResource.company;

        settings.DataBinding = (sender, e) =>
        {
            ((MVCxGridView)sender).ForceDataRowType(typeof(EditUserViewModel));
        };
    });
    if (ViewData["GenericError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["GenericError"]);
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 56 "..\..\Views\Account\UsersList.cshtml"
Write(grid.Bind(Model).GetHtml());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
