#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.UI.WebControls;
    using System.Web.WebPages;
    using DevExpress.Utils;
    using DevExpress.Web;
    using DevExpress.Web.ASPxThemes;
    using DevExpress.Web.Mvc;
    using DevExpress.Web.Mvc.UI;
    
    #line 2 "..\..\Views\Account\UserRoles.cshtml"
    using IWSProject.Content;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/UserRoles.cshtml")]
    public partial class _Views_Account_UserRoles_cshtml : System.Web.Mvc.WebViewPage<IWSProject.Models.UserRolesViewModel>
    {
        public _Views_Account_UserRoles_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("    ");

WriteLiteral("\r\n<h2>");

            
            #line 4 "..\..\Views\Account\UserRoles.cshtml"
Write(IWSLocalResource.User);

            
            #line default
            #line hidden
WriteLiteral(" : ");

            
            #line 4 "..\..\Views\Account\UserRoles.cshtml"
                        Write(Html.DisplayFor(model => model.UserName));

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n<hr />\r\n\r\n");

            
            #line 7 "..\..\Views\Account\UserRoles.cshtml"
 using (Html.BeginForm("UserRoles", "Account", FormMethod.Post, new { encType = "multipart/form-data", name = "myform" }))
{
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\UserRoles.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\UserRoles.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-horizontal\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 12 "..\..\Views\Account\UserRoles.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 15 "..\..\Views\Account\UserRoles.cshtml"
           Write(Html.HiddenFor(model => model.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <h4>");

            
            #line 18 "..\..\Views\Account\UserRoles.cshtml"
       Write(IWSLocalResource.RolesAssignement);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n        <hr />\r\n        <table>\r\n            <tr>\r\n                <th></t" +
"h>\r\n                <th></th>\r\n            </tr>\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Account\UserRoles.cshtml"
       Write(Html.EditorFor(model => model.Roles));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </table>\r\n        <br /><br />\r\n        <hr />\r\n        ");

WriteLiteral("\r\n    </div>\r\n");

            
            #line 35 "..\..\Views\Account\UserRoles.cshtml"

    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Account\UserRoles.cshtml"
Write(Html.DevExpress().Button(settings =>
{
    settings.Name = "btnSubmit";
    settings.Text = IWSLocalResource.Validate;
    settings.Width = Unit.Pixel(150);
    settings.UseSubmitBehavior = true;
    //settings.ClientSideEvents.Click = "OnSubmitClick";
}).GetHtml());

            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Account\UserRoles.cshtml"
            
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
